# Generated by Django 4.2.11 on 2024-04-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('content', models.TextField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
